### ISSUE TITLE
[feature request] support invertOnOffIds

### ISSUE THREAD

**Issue by blysik** [Colorado4Wheeler/Homebridge#1]
Hi, this is a feature request to support the homebridge-indigo setting "invertOnOffIds".  I use the MyQ plugin to handle my garage door, and that uses the locked/unlocked settings, and requires inverting the value to play nice with homekit.

**Comment by Colorado4Wheeler** [comment]
It's in RC6 released today, it was always planned for when the built-in HB was released.
